name: easy_pass
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  
  # 功能性插件
  http: ^0.13.3 # http包
  dio: ^4.0.0   # http包
  shared_preferences: ^2.0.5  # 状态存储
  flutter_svg: ^0.21.0  # svg图片解析
  local_auth: ^1.1.6  # 生物识别登录
  barcode_scan2: ^4.1.3    # 二维码识别

  # UI相关插件
  inkwell_splash: ^0.1.0  # 带有波纹的按钮
  fluttertoast: ^8.0.7    # toast功能
  font_awesome_flutter: ^9.0.0  # awesome图标
  styled_widget: ^0.3.1 # 提供更易用的style写法
  fsuper: ^2.0.2  # 和文本相关的UI组件
  motion_tab_bar: ^0.1.5 # 底栏
  neuomorphic_container: ^2.0.3 # 卡片Container
  useful_widgets: ^1.2.0  # 功能性组件
  filter_list: ^1.0.0 # 标签筛选功能
  flutter_staggered_animations: ^1.0.0  # 加载动画
  # groovin_widgets: ^2.0.0 # 功能性控件，如下拉框
  toggle_switch: "^0.1.9" # switch按钮


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/logo/
    - assets/images/icon/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Oppo Sans
      fonts:
        - asset: assets/fonts/OppoSans/OPPOSans-L.ttf
          weight: 300
        - asset: assets/fonts/OppoSans/OPPOSans-R.ttf
        - asset: assets/fonts/OppoSans/OPPOSans-M.ttf
          weight: 500
        - asset: assets/fonts/OppoSans/OPPOSans-B.ttf
          weight: 700
        - asset: assets/fonts/OppoSans/OPPOSans-H.ttf
          weight: 800
    - family: Jiangcheng
      fonts:
        - asset: assets/fonts/Jiangcheng/Jiangcheng-200W.ttf
          weight: 200
        - asset: assets/fonts/Jiangcheng/Jiangcheng-300W.ttf
          weight: 300
        - asset: assets/fonts/Jiangcheng/Jiangcheng-400W.ttf
          weight: 400
        - asset: assets/fonts/Jiangcheng/Jiangcheng-500W.ttf
          weight: 500
        - asset: assets/fonts/Jiangcheng/Jiangcheng-600W.ttf
          weight: 600
        - asset: assets/fonts/Jiangcheng/Jiangcheng-700W.ttf
          weight: 700
        
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
